### PR TITLE
Update to Pyro

### PR DESCRIPTION
**Pull request by willnewton**

### CODE REVIEW

**Comment by willnewton** [comment]
This still requires a meta-resin release.

**Comment by agherzan** [comment]
@willnewton is the latest meta-resin OK now for pyro support?

**Comment by willnewton** [comment]
@agherzan it is for non-flasher images, flasher images will require 2.6.1

**Comment by agherzan** [comment]
Got it. Will release today.

**Comment by agherzan** [comment]
@willnewton here you go: https://github.com/resin-os/meta-resin/releases/tag/v2.6.1

**Comment by willnewton** [comment]
@agherzan thanks, rebased

**Pull request merged**
